#服务端口配置
server:
  port: 8888

# 登陆用户名和密码配置
apploginuser:
  username: admin
  password: 123456

#自定义的连接池配置
defhikariconfig:
    ## 最小空闲连接数量
  minimumIdle: 5
  ## 连接池最大连接数，默认是10
  maximumPoolSize: 10
    ## 连接允许在池中闲置的最长时间，0表示永久允许闲置,默认600000（10分钟）
  idleTimeout: 180000
    ## 从连接池取出连接的最长等待时间，超过此事件则会报错,默认30秒，即30000
  connectionTimeout: 30000
    ## 只读模式
  readOnly: true


#配置级别为trace，控制台打印所有级别日志  TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    top.hudk.dictionary: DEBUG
  path: ./logs
   #com.wang.logging : trace