server:
  port: 8888


apploginuser:
  username: admin
  password: 123456



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sql_test
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
